### ISSUE TITLE
StackOverFlowQuickLaunch does not show any result

### ISSUE THREAD

**Issue by RicardoBritoBrens** [aberus/StackOverflowQuickLaunch#3] opened 2018-11-29 18:56 UTC
Hello hello, Mi name is Ricardo

I'm using this awesome plugin for a short time and when i use without using a proxy it works perfect, but  now a i'm using one and when i search i'm getting any result, here is my actual configuration.

![screenshot_1](https://user-images.githubusercontent.com/20712658/49244687-c51f7180-f3e6-11e8-9b61-57846f02184f.png)

![screenshot_2](https://user-images.githubusercontent.com/20712658/49244690-c81a6200-f3e6-11e8-8207-46c7f1560729.png)

I hope you answer my question.

Best Regards

**Comment by aberus** [comment] 2018-12-20 11:55
Hi.

I'll look into [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) if it has problem resolving proxy.

When you have turned on a proxy, can you access https://api.stackexchange.com/. Maybe the problem is that a proxy doesn't allow you access to the address above?

**Closed as completed** 2019-08-02 09:23 UTC
